[WIP]READMEの編集
akmatsumoto/chat-space pull request #1
Opened 2019-05-05 23:59 UTC by akmatsumoto

#WHAT
READMEの編集をする。

#WHY
データベースの設計を行うため。

2019-05-06 01:40 UTC, yuki-uchida requested changes

2019-05-06 01:40 UTC, yuki-uchida commented on README.md
> +|image|string|null: true|
1度、テーブル同士がどのような関係になっているか、ER図を書いてみましょう
Groupsテーブルとの関係、Userテーブルとの関係が抜けています

2019-05-06 01:40 UTC, yuki-uchida commented on README.md
> +|group_id|integer|null: false, foreign_key: true|
外部キー制約をつけたい場合にはrefferences型としましょう

2019-05-07 00:10 UTC, akmatsumoto commented on README.md
> +|group_id|integer|null: false, foreign_key: true|
修正しました

2019-05-07 00:12 UTC, akmatsumoto commented on README.md
> +|image|string|null: true|
messagesテーブルにuser_idカラムとgroup_idカラムの追加、
groupsテーブルとmessagesテーブルのアソシエーションを追加修正しました。

2019-05-07 01:59 UTC, TOMARUMARU commented on README.md
> +|body|text|null: false|
画像だけで保存できなくなるので、null falseは外しましょう

2019-05-07 23:28 UTC, akmatsumoto commented on README.md
> +|body|text|null: false|
修正しました

2019-05-08 01:53 UTC, miyagit approved these changes
LGTM

2019-05-10 16:50 UTC, merged